version: "3"

services:
  crypto-jvm:
    image: quarkus/crypto-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-crypto:3306/crypto_negotiation?autoReconnect=true
    networks:
      - mysql-db
    ports:
      - 8080:8080
    depends_on:
      - mysql-crypto

  mysql-crypto:
    image: aluracursos/mysql-quarkus-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.crypto:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

networks:
  mysql-db:
    driver: bridge

volumes:
  mysql.crypto:
